server:
  port: 8080

zk:
  url: 10.0.0.241:2181
  namespace: valjean

app:
  id: app1
  env: dev
  namespace: public


zvrpc:
  providers: http://localhost:8070,http://localhost:8071

logging:
  level:
    root: info
    cn.valjean.rpc: debug
